### PR TITLE
update youtube-dl binary 2020.11.01.1

### PR DESCRIPTION
**Pull request by xibr**
Youtube-dl cannot be updated automatically so you must update manually.

### CODE REVIEW

**Comment by xibr** [comment]
version bump

**Comment by gomikestrat** [comment]
i tried with https://youtu.be/zqI0LQcm7AQ and im getting `error com.yausername.youtubedl_android.YoutubeDLException: ERROR: zqI0LQcm7AQ: YouTube said: Unable to extract video data`

**Comment by xibr** [comment]
> i tried with https://youtu.be/zqI0LQcm7AQ and im getting `error com.yausername.youtubedl_android.YoutubeDLException: ERROR: zqI0LQcm7AQ: YouTube said: Unable to extract video data`

Did you update youtube-dl binary 2010.11.01.1 ?

**Comment by gomikestrat** [comment]
i tried with your latest commit, used jitpack and edited build.gradle accordingly:
implementation 'com.github.xibr.youtubedl-android:library:a718cc81b4'

**Comment by xibr** [comment]
It's work fine.
`implementation 'com.github.xibr.youtubedl-android:library:a718cc81b4'`
 



Try removing temporary files or app data and try again.

**Comment by yausername** [comment]
Thanks @xibr
I have also fixed auto update for the time being.

**Comment by xibr** [comment]
Thank you for fix the auto update.

**Pull request merged**
