### PR TITLE
android 10 support, x86 support

### PR DESCRIPTION
**Pull request by yausername**
Hi everyone,

I have hacked my way into fixing #26. I will research on better ways to fix it.
For now I need help in testing this on android 10 and older versions.

Testing APKs (size is ~33MB because they contain python+ffmpeg)
[ARM](https://github.com/yausername/files/blob/master/apks/app-armeabi-debug.apk)
[x86](https://github.com/yausername/files/blob/master/apks/app-x86-debug.apk)
If it works I will do a release tomorrow. I welcome code reviews or any other suggestions.

Key points
* This is a breaking change. It is not backward compatible with older installations. You will have to uninstall older version or clear data before launching app if you are updating.
* I have also added x86 support along with this change.
* You need to add `android:extractNativeLibs="true"` to android manifest, see sample app.
* You need to use `abiFilters 'x86', 'armeabi'` in build.gradle, see sample app.
* You need to use `android:allowBackup="false"` in android manifest or exclude `files/youtubedl-android` directory from auto backup.
* You should use abi splits to reduce apk size, see sample app.

### CODE REVIEW

**Comment by rcaselles** [comment]
I have tested this in Android Q, I have updated youtube-dl but the download still keeps failing, the streaming mode is working

**Comment by rcaselles** [comment]
Also, i dont get any sound in streaming

**Comment by rcaselles** [comment]
Update: It seems it has more to do with Writing permissions:
command failed : com.yausername.youtubedl_android.YoutubeDLException: ERROR: unable to open for writing: [Errno 13] Permission denied: '/sdcard/Download/[...}

**Comment by yausername** [comment]
> Also, i dont get any sound in streaming

I am using the first mp4 link I get for streaming example. It is possible it might not have sound. Since this is just an example I have not handled all such cases.

> Update: It seems it has more to do with Writing permissions:

I have used `android:requestLegacyExternalStorage="true"` as a temporary fix for opting out of scoped storage. The apks above are updated. Please test and let me know.

Thanks

**Comment by rcaselles** [comment]
Working perfect in Android Q, both via command and link. Thank you!

**Comment by CoreyVidal** [comment]
On Android 10, using Samsung Galaxy Note 10+. Using the arm .APK you provided in this thread.  
  
Here's the video URL I chose:  
https://youtu.be/I4FXzSPbVKE  
 
"START STREAM":  
  
It loads the video with correct run-time, but the video is black and there is no audio.  
 
"START DOWNLOAD"  
 
Worked perfectly.  
 
"UPDATE YOUTUBE-DL"  
  
I got "download failed" every time.

**Comment by bunaif** [comment]
@yausername hi, I'm testing on android 10 Samsung Galaxy s9 plus, working fine, but streaming work without sound I think this is not a problem.

**Comment by bunaif** [comment]
also testing on android 9 and work fine.

> Also, i dont get any sound in streaming

add somethings like this in StreamingExampleActivity.java in getVideoUrl line 110
`f.formatId.equals("22") || f.formatId.equals("18")`

**Comment by yausername** [comment]
Hi,
Thanks guys for testing.
I've changed the streaming example to use youtube-dl option `-f best`. This should work for most videos.
The apk links are above.

**Comment by yausername** [comment]
> "UPDATE YOUTUBE-DL"
> 
> I got "download failed" every time.

This is wierd. Are you still getting this error?
If yes, can you do a `clear cache, clear data` and try again?

**Comment by CoreyVidal** [comment]
I just updated to the newest APK (as of 4:45 PM Eastern). The streaming for YouTube now works perfectly (video and audio). And "UPDATE YOUTUBE-DL" now also works perfectly. Awesome.

However, this Reddit video was working in streaming earlier today (run-time and audio, but not video), but now no longer works at all:

https://v.redd.it/08f6zttg02w41/DASHPlaylist.mpd

**Comment by bunaif** [comment]
> I've changed the streaming example to use youtube-dl option -f best. This should work for most videos.

now working video with audio 👍

**Comment by bunaif** [comment]
> Here's the video URL I chose:
https://youtu.be/I4FXzSPbVKE
"START STREAM":
It loads the video with correct run-time, but the video is black and there is no audio.

fixed now.

**Comment by yausername** [comment]
> However, this Reddit video was working in STRRAMING earlier today (run-time and audio worked, but not video), however now it no longer works at all:

With the `-f best` option, it only works for videos where a single link containing both audio and video is available. In this case reddit does not provide a single link.  I might have to look into streaming using different audio and video links.

**Comment by CoreyVidal** [comment]
Hey, can you continue to generate .APKs? I'm not a developer, just someone who wants an easy youtube-dl on his phone. No idea how to make my own. But the test/debug APKs you were posting were great.

**Comment by yausername** [comment]
Sure, I will add apk links to the readme for easy access.

**Comment by morhadi** [comment]
[> Sure, I will add apk links to the readme for easy access.
](https://github.com/yausername/youtubedl-android/pull/43#issuecomment-623123591)

Why don't you give direct APK anymore?

**Pull request merged**
