### PR TITLE
Allow update from nightly or stable channel

### PR DESCRIPTION
**Pull request by kadwanev**
Sometimes, you want to run the nightly build. This adds the ability to switch channels and a dialog in the example.

### CODE REVIEW

**Comment by kadwanev** [comment]
@xibr @JunkFood02 Would you take a look and provide any feedback?

**Comment by xibr** [comment]
Well, I like the idea, I'll take a look when I have some free time.

**Comment by JunkFood02** [comment]
actually I've been implemented this in my fork but it's haven't merged yet

**Comment by kadwanev** [comment]
Thanks!

**Pull request merged**
