### PR TITLE
Add mutagen

### LINKED ISSUE #150: Request Mutagen for embed-thumbnail
embed-thumbnail doesn't work for .opus

config.txt
`-f 251 --extract-audio --audio-format opus --audio-quality 0 --embed-thumbnail  --add-metadata -v -o "/sdcard/youtube-dl/%(creator)s - %(title)s.%(ext)s"`

log
`[debug] Command-line config: ['--config-location', '/storage/emulated/0/Download/youtubedl-android/config.txt', '--no-cache-dir', 'https://youtu.be/fZ5izx5vdeY']
[debug] | Config "/storage/emulated/0/Download/youtubedl-android/config.txt": ['-f', '251', '--extract-audio', '--audio-format', 'opus', '--audio-quality', '0', '--embed-thumbnail', '--add-metadata', '-v', '-o', '/sdcard/youtube-dl/%(creator)s - %(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Python version 3.8.0 (CPython 64bit) - Linux-4.9.277-caf+-aarch64-with-libc
[debug] Checking exe version: libffmpeg.bin.so -bsfs
[debug] Checking exe version: libffprobe.bin.so -bsfs
[debug] exe versions: libffmpeg.bin.so 4.2.1, libffprobe.bin.so 4.2.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/fZ5izx5vdeY
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
[debug] libffmpeg.bin.so command line: libffprobe.bin.so -show_streams 'file:/sdcard/youtube-dl/NA - Drakan - Order of the Flame OST - 01 - Wartok Canyons.opus'
[debug] ffmpeg command line: libffmpeg.bin.so -y -loglevel repeat+info -i 'file:/sdcard/youtube-dl/NA - Drakan - Order of the Flame OST - 01 - Wartok Canyons.opus' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Drakan: Order of the Flame OST - 01 - Wartok Canyons' -metadata date=20120613 -metadata 'description=Composers: Tim Ebling & B.L.A.S.T.
Copyright: Pysgnosis and Surreal Software

The track featured in the level: Wartok Canyons.' -metadata 'synopsis=Composers: Tim Ebling & B.L.A.S.T.
Copyright: Pysgnosis and Surreal Software

The track featured in the level: Wartok Canyons.' -metadata 'purl=https://www.youtube.com/watch?v=fZ5izx5vdeY' -metadata 'comment=https://www.youtube.com/watch?v=fZ5izx5vdeY' -metadata artist=RavagerDX -movflags +faststart 'file:/sdcard/youtube-dl/NA - Drakan - Order of the Flame OST - 01 - Wartok Canyons.temp.opus'
ERROR: Postprocessing: module mutagen was not found. Please install using `python -m pip install mutagen`
Traceback (most recent call last):
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/YoutubeDL.py", line 3211, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/YoutubeDL.py", line 3379, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/YoutubeDL.py", line 3366, in run_all_pps
    info = self.run_pp(pp, info)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/YoutubeDL.py", line 3339, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/postprocessor/common.py", line 27, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/postprocessor/common.py", line 124, in wrapper
    return func(self, info)
  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 204, in run
    raise EmbedThumbnailPPError('module mutagen was not found. Please install using `python -m pip install mutagen`')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: module mutagen was not found. Please install using `python -m pip install mutagen``

Option `--compat-options embed-thumbnail-atomicparsley` didn't help me

### PR DESCRIPTION
**Pull request by xibr**
Fixes #150

I have added [mutagen](https://github.com/quodlibet/mutagen) to `/usr/lib/python3.8/site-packages/`

### CODE REVIEW

**Comment by yausername** [comment]
Could we document the steps in this https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md ?

**Review by yausername — APPROVED** [review]
Looks good. It will be good to document the steps.

**Comment by xibr** [comment]
> Could we document the steps in this https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md ?

Done, is that good?

**Comment by yausername** [comment]
> > Could we document the steps in this https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md ?
> 
> Done, is that good?

Yes, this will do.

Thanks.

**Pull request merged**
