### PR TITLE
Add Aria2

### PR DESCRIPTION
**Pull request by xibr**
close https://github.com/yausername/youtubedl-android/issues/177

### CODE REVIEW

**Comment by xibr** [comment]
@JunkFood02 Can you test this?
 
include and initialize the aria2c library.
```java
Aria2c.getInstance().init(this);
```

```gradle
implementation 'com.github.xibr.youtubedl-android:aria2c:fc01d681a8'
```

**Comment by JunkFood02** [comment]
```
WARNING: [youtube] MXlsgBNRTR4: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 4YKttGoUoUcZOX1T3iWd7 ; player = https://www.youtube.com/s/player/f96f6702/player_ias.vflset/en_US/base.js
CANNOT LINK EXECUTABLE "libaria2c.so": library "libcares.so" not found: needed by main executable



ERROR: aria2c exited with code 1
CANNOT LINK EXECUTABLE "libaria2c.so": library "libcares.so" not found: needed by main executable



ERROR: aria2c exited with code 1
```

**Comment by xibr** [comment]
Just add 
```gradle
implementation 'com.github.xibr.youtubedl-android:aria2c:4b7974c61f'
implementation 'com.github.xibr.youtubedl-android:library:4b7974c61f'
```
Because we modified [YoutubeDL.java](https://github.com/xibr/youtubedl-android/blob/aria2c/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java) in [#L81](https://github.com/xibr/youtubedl-android/blob/4b7974c61fe89e65af75ea7fc654b82335bcc9a4/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java#L81)

**Comment by JunkFood02** [comment]
I guess you're attempting to make aria2c and FFmpeg link to same `.so` libraries to reduce the libraries? No idea about where's the problem. Is the version of the `.so` matters?

```
val youtubedlAndroidVersion = "4b7974c61f"
implementation ("com.github.xibr.youtubedl-android:library:$youtubedlAndroidVersion")
implementation ("com.github.xibr.youtubedl-android:ffmpeg:$youtubedlAndroidVersion")
implementation ("com.github.xibr.youtubedl-android:aria2c:$youtubedlAndroidVersion")
```

```
CANNOT LINK EXECUTABLE "libaria2c.so": library "libc++_shared.so" not found: needed by main executable



ERROR: aria2c exited with code 1
CANNOT LINK EXECUTABLE "libaria2c.so": library "libc++_shared.so" not found: needed by main executable



ERROR: aria2c exited with code 1
```

**Comment by JunkFood02** [comment]
`aa680fbdd0` works fine so far

**Comment by xibr** [comment]
Yes, I tested it on Android 5 (`armeabi-v7a`) and Android 9 (`arm64-v8a`) and I didn't find any problem.

**Pull request merged**
