### PR TITLE
Option to use config file

### PR DESCRIPTION
**Pull request by xibr**
add option to use config file in the download option closes [https://github.com/yausername/youtubedl-android/issues/85](https://github.com/yausername/youtubedl-android/issues/85)

### CODE REVIEW

**Review by yausername — APPROVED** [review]
LGTM

**Comment by xibr** [comment]
should i publish release 0.12.4 and upload apks? To use the latest changes.

**Comment by yausername** [comment]
Sure, go ahead.
I'm not finding time to do myself.
Thanks.

**Comment by xibr** [comment]
Thanks, I will do that, I have a lot of free time 😁

**Pull request merged**
