### PR TITLE
updated the libs to python version 3.11

### PR DESCRIPTION
**Pull request by syedusama5556**
all the libs have been updated to python version 3.11

### CODE REVIEW

**Comment by zaednasr** [comment]
@syedusama5556 have you noticed speed improvements?

**Comment by zaednasr** [comment]
What I'm most concerned is data fetching
Currently if i try to print formats it might take up to 8 seconds but on PC takes 4

**Comment by zaednasr** [comment]
@syedusama5556 3.12 is possible?

**Comment by zaednasr** [comment]
The c++ idea seems interesting. Any idea how it can be achieved?

**Comment by zaednasr** [comment]
Any updates on the other python versions?
yt-dlp just deprecated 3.8, we need to apply this soon

**Comment by xibr** [comment]
It seems that the libpython.zip.so file is too big and also mutagen is missing.

What about pycryptodomex??

**Comment by zaednasr** [comment]
he probably followed bobby's guide and he included many libraries:
python_3.11.9-5_aarch64.deb
libandroid-posix-semaphore_0.1-3_aarch64.deb
libandroid-support_29_aarch64.deb
libffi_3.4.6-1_aarch64.deb
zlib_1.3.1_aarch64.deb
openssl_1:3.3.1_aarch64.deb
ca-certificates_1:2024.07.02_all.deb

So that could be why its so large.

**Comment by xibr** [comment]
> he probably followed bobby's guide and he included many libraries:
> python_3.11.9-5_aarch64.deb
> libandroid-posix-semaphore_0.1-3_aarch64.deb
> libandroid-support_29_aarch64.deb
> libffi_3.4.6-1_aarch64.deb
> zlib_1.3.1_aarch64.deb
> openssl_1:3.3.1_aarch64.deb
> ca-certificates_1:2024.07.02_all.deb
> 
> So that could be why its so large.
> 

I think he didn't delete the `__pycache__` That's why the file seems to `libpython.zip.so` so large.

**Comment by xibr** [comment]
> yes i did followed his guide, can you list which libraries do we need so we can reduce the size, and i tested it in the app its working fine even without mutagen for now but the size is larger now.

Have you taken a look at branch [update-library](https://github.com/yausername/youtubedl-android/tree/update-library)?

Also when upgrading to Python 3.11 Android 5 and 6 will be deprecated and aria2 must be updated as well.

**Comment by xibr** [comment]
If you want to build Python with small size `maybe 8.5 MB` use this
```
https://packages.termux.dev/apt/termux-main/pool/main/o/openssl/
https://packages.termux.dev/apt/termux-main/pool/main/p/python/
https://packages.termux.dev/apt/termux-main/pool/main/liba/libandroid-support/
https://packages.termux.dev/apt/termux-main/pool/main/liba/libandroid-posix-semaphore/
https://packages.termux.dev/apt/termux-main/pool/main/z/zlib/
https://packages.termux.dev/apt/termux-main/pool/main/libf/libffi/
https://packages.termux.dev/apt/termux-main/pool/main/c/ca-certificates/
https://packages.termux.dev/apt/termux-main/pool/main/libe/libexpat/
```

But I tried this and it works without any problem
```
https://packages.termux.dev/apt/termux-main/pool/main/o/openssl/
https://packages.termux.dev/apt/termux-main/pool/main/libl/liblzma/
https://packages.termux.dev/apt/termux-main/pool/main/r/readline/
https://packages.termux.dev/apt/termux-main/pool/main/p/python/
https://packages.termux.dev/apt/termux-main/pool/main/libs/libsqlite/
https://packages.termux.dev/apt/termux-main/pool/main/libc/libcrypt/
https://packages.termux.dev/apt/termux-main/pool/main/liba/libandroid-support/
https://packages.termux.dev/apt/termux-main/pool/main/liba/libandroid-posix-semaphore/
https://packages.termux.dev/apt/termux-main/pool/main/z/zlib/
https://packages.termux.dev/apt/termux-main/pool/main/n/ncurses/
https://packages.termux.dev/apt/termux-main/pool/main/libf/libffi/
https://packages.termux.dev/apt/termux-main/pool/main/libb/libbz2/
https://packages.termux.dev/apt/termux-main/pool/main/g/gdbm/
https://packages.termux.dev/apt/termux-main/pool/main/c/ca-certificates/
https://packages.termux.dev/apt/termux-main/pool/main/libe/libexpat/
```

Before creating the **python_arm64.zip** file, run this command:
```find . | grep -E "(/__pycache__$|/SelfTest$|/ensurepip$|/pydoc_data$|\.pyc$|\.ctypes$|\.pyo$|\.pyi$|\.typed$|/test$|/tests$/|cmake$|/pkgconfig$|/unittest$|/config-3.11$|\terminfo$|\LICENSE.txt$|\README.txt$)" | xargs rm -rf```

This deletes folders and files that we don't need.

**Comment by JunkFood02** [comment]
> Have you taken a look at branch [update-library](https://github.com/yausername/youtubedl-android/tree/update-library)?

that's my experiment and haven't found a way to automate this process yet

**Comment by xibr** [comment]
Check [bump-python-3.11.10](https://github.com/yausername/youtubedl-android/tree/[bump-python-3.11.10)

**Comment by JunkFood02** [comment]
#298

**Pull request closed without merging**
